//POSTS
export const FETCH_POSTS = "FETCH_POSTS";
export const NEW_POST = "NEW_POST";

//DATAMUSE
export const FETCH_WORDS = "FETCH_WORDS";
export const FETCH_MEANING_SIMILAR = "FETCH_MEANING_SIMILAR";

//USAGE
export const TOGGLE_WORDS = "TOGGLE_WORDS";
export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";

export const VisibilityFilters = {
  SHOW_ALL: "SHOW_ALL",
  SHOW_COMPLETED: "SHOW_COMPLETED",
  SHOW_ACTIVE: "SHOW_ACTIVE",
};
