//POSTS
export const FETCH_POSTS = 'FETCH_POSTS';
export const NEW_POST = 'NEW_POST';

//DATAMUSE
export const FETCH_WORDS = 'FETCH_WORDS';
export const FETCH_MEANING_SIMILAR = 'FETCH_MEANING_SIMILAR';

//USAGE
export const TOGGLE_WORDS = 'TOGGLE_WORDS';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';

export const VisibilityFilters = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
  SHOW_ACTIVE: 'SHOW_ACTIVE',
};

//ALERT
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

//USER
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

//LIST
export const SUBMIT_ITEM = 'SUBMIT_ITEM';
export const ABOVE_ITEM = 'ABOVE_ITEM';
export const LOAD_ITEM = 'LOAD_ITEM';
export const SORT_ITEMS = 'SORT_ITEMS';
export const SET_ITEM_FILTER = 'SET_ITEM_FILTER';
export const FILTERED_LIST = 'FILTERED_LIST';

